name: Upload Sourcemaps to PostHog

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["Deploy to NuxtHub"]
    types: [completed]
    branches: [main]

jobs:
  upload-sourcemaps:
    name: "Upload Sourcemaps to PostHog"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Download and install PostHog CLI
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/PostHog/posthog/releases/download/posthog-cli-v0.0.5/posthog-cli-installer.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build application
        run: pnpm build
        env:
          POSTHOG_CLI_ENV_ID: ${{ env.POSTHOG_CLI_ENV_ID }}
          POSTHOG_CLI_TOKEN: ${{ env.POSTHOG_CLI_TOKEN }}

      - name: Upload sourcemaps to PostHog
        run: |
          posthog-cli sourcemap upload --directory dist/public
        env:
          POSTHOG_CLI_ENV_ID: ${{ env.POSTHOG_CLI_ENV_ID }}
          POSTHOG_CLI_TOKEN: ${{ env.POSTHOG_CLI_TOKEN }}

      - name: Clean up build artifacts
        run: rm -rf .output
